### PR TITLE
Update UrlExpander.cs

### PR DESCRIPTION
**Pull request by geekyrudh**
Removed a redundant method, and cleared out the conditional block.
Why do I feel like I'm doing something wrong? :/

### CODE REVIEW

**Comment by bhavika** [comment]
Don't worry! I'll test in a bit and merge.

**Comment by bhavika** [comment]
Your changes break one test case - expanding a URL shortened twice. That's transitivity. 
Say you have a NYTimes link that you first shorten with bit.ly and the shortened bit.ly URL you further pass to goo.gl, the URLExpander should return the NYTimes link as that is the final destination. 

Shorten-
NYTimes link -> goo.gl -> bit.ly

Expand-

bit.ly -> NYTimes link

I'm closing this PR. It doesn't mean I haven't repeated code but the function you removed was taking care of the transitive case.

**Comment by geekyrudh** [comment]
Got it. Thank you for the explanation :)
Theoretically, someone could chain such shorteners one after the other, much like malvertisers do. Should a recursive/iterative method be employed to keep looking for further redirections until the final URI is reached?

**Comment by bhavika** [comment]
Yes. We do need a recursive method. I have not tested my code for more than 2 levels of shortening but that's fairly simple to do.

**Pull request closed without merging**
